/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ClasseInfo {
  breakpoint?: string
  classeName?: string
  size?: string
}
export declare function sum(a: number, b: number): number
export declare class Parser {
  constructor(classesInfo: Array<ClasseInfo>)
  parse(): void
}
export declare class Scanner {
  constructor(code: string)
  scan(): Array<ClasseInfo>
  findClass(classes: Array<string>): Array<ClasseInfo>
}
export declare class ScannerOutput { }
